import type { BenchmarkScore, BenchmarkCountrySummary } from "@/types/benchmark";
import { BENCHMARK_CLUSTERS } from "@/lib/constants";
import { DIGITAL_2_DOZEN_PRINCIPLES } from "@/lib/digital2dozen";

/**
 * Compliance scores for all 11 ASEAN countries × 24 Digital 2 Dozen principles.
 * Scores: 0-20 = Severely Non-Compliant | 21-40 = Mostly Non-Compliant
 *         41-60 = Mixed/Partial | 61-80 = Mostly Compliant | 81-100 = Fully Compliant
 *
 * Data sources: OECD DSTRI, Freedom House, national legislation databases,
 * ASEAN Secretariat DEFA documents, CPTPP ratification records.
 * Last reviewed: 2026-07-29
 */

export const BENCHMARK_SCORES: BenchmarkScore[] = [
  // ══════════════════════════════════════════════════════════════
  // SINGAPORE (SG) — CPTPP Member, DEPA Co-Founder, DEFA Leader
  // ══════════════════════════════════════════════════════════════
  // P1-4 Infrastructure
  { countryCode: "SG", principleId: 1, score: 95, evidence: "No content blocking. IMDA promotes open internet access. Rare discretionary blocking limited to gambling and extremist content.", sourceUrl: "https://www.imda.gov.sg", lastReviewed: "2026-07-29" },
  { countryCode: "SG", principleId: 11, score: 90, evidence: "Highly competitive telecom market. Multiple submarine cable landings. Singtel, StarHub, M1, and MVNOs compete freely.", sourceUrl: "https://www.imda.gov.sg", lastReviewed: "2026-07-29" },
  { countryCode: "SG", principleId: 17, score: 100, evidence: "WTO ITA signatory. Zero tariffs on ICT products. Free port — almost all manufactured goods enter duty-free.", sourceUrl: "https://www.customs.gov.sg", lastReviewed: "2026-07-29" },
  { countryCode: "SG", principleId: 18, score: 95, evidence: "TradeNet single-window system. Paperless e-customs pioneer. Express shipment processing within minutes.", sourceUrl: "https://www.customs.gov.sg", lastReviewed: "2026-07-29" },
  // P5-8 Data Governance
  { countryCode: "SG", principleId: 2, score: 100, evidence: "No digital service taxes or customs duties on electronic transmissions. WTO moratorium supporter.", sourceUrl: "https://www.mti.gov.sg", lastReviewed: "2026-07-29" },
  { countryCode: "SG", principleId: 3, score: 90, evidence: "Strong non-discrimination commitment. Foreign digital service providers operate freely. No local incorporation requirements for digital services.", sourceUrl: "https://www.mti.gov.sg", lastReviewed: "2026-07-29" },
  { countryCode: "SG", principleId: 4, score: 95, evidence: "Open data transfer regime. APEC CBPR certified. ASEAN MCCs leader. PDPA permits transfers with accountability.", sourceUrl: "https://www.pdpc.gov.sg", lastReviewed: "2026-07-29" },
  { countryCode: "SG", principleId: 5, score: 100, evidence: "No data localization requirements. Explicitly opposes localization in DEFA negotiations. Cloud providers operate freely.", sourceUrl: "https://www.imda.gov.sg", lastReviewed: "2026-07-29" },
  { countryCode: "SG", principleId: 13, score: 90, evidence: "DEPA modular framework co-creator. Forward-looking digital economy agreements with UK, Korea, Australia, EU.", sourceUrl: "https://www.mti.gov.sg", lastReviewed: "2026-07-29" },
  { countryCode: "SG", principleId: 14, score: 95, evidence: "Full market access for foreign cloud, consulting, advertising services. No local presence requirements for digital services.", sourceUrl: "https://www.mti.gov.sg", lastReviewed: "2026-07-29" },
  // P9-12 Tech Sovereignty
  { countryCode: "SG", principleId: 6, score: 95, evidence: "No forced technology transfer requirements. IP regime protects proprietary technology.", sourceUrl: "https://www.ipos.gov.sg", lastReviewed: "2026-07-29" },
  { countryCode: "SG", principleId: 7, score: 90, evidence: "No mandatory source code disclosure. AI Verify is voluntary. Algorithmic audit framework is opt-in.", sourceUrl: "https://www.imda.gov.sg", lastReviewed: "2026-07-29" },
  { countryCode: "SG", principleId: 8, score: 90, evidence: "Technology-neutral regulations. No mandated local technology standards. Market-driven tech adoption.", sourceUrl: "https://www.imda.gov.sg", lastReviewed: "2026-07-29" },
  { countryCode: "SG", principleId: 9, score: 95, evidence: "Electronic Transactions Act supports diverse e-signature methods. SingPass/CorpPass for digital identity.", sourceUrl: "https://www.imda.gov.sg", lastReviewed: "2026-07-29" },
  { countryCode: "SG", principleId: 12, score: 90, evidence: "No encryption backdoor mandates. Strong encryption products freely available. Cybersecurity Act focuses on CII protection, not encryption weakening.", sourceUrl: "https://www.csa.gov.sg", lastReviewed: "2026-07-29" },
  // P13-16 Consumer Trust
  { countryCode: "SG", principleId: 10, score: 90, evidence: "PDPA provides enforceable consumer protections. Do Not Call registry. Consumer Protection (Fair Trading) Act.", sourceUrl: "https://www.pdpc.gov.sg", lastReviewed: "2026-07-29" },
  { countryCode: "SG", principleId: 15, score: 95, evidence: "ASEAN cybersecurity leader. CSA coordinates threat sharing. Active CERT. ASEAN-Singapore Cybersecurity Centre of Excellence.", sourceUrl: "https://www.csa.gov.sg", lastReviewed: "2026-07-29" },
  { countryCode: "SG", principleId: 19, score: 85, evidence: "Public consultations on digital regulations. REACH feedback platform. However, limited civil society engagement on security laws.", sourceUrl: "https://www.reach.gov.sg", lastReviewed: "2026-07-29" },
  { countryCode: "SG", principleId: 20, score: 80, evidence: "Temasek-linked companies (Singtel) compete commercially. Government-linked corporations operate on commercial basis. GLC governance framework.", sourceUrl: "https://www.mti.gov.sg", lastReviewed: "2026-07-29" },
  // P17-20 IP & Standards
  { countryCode: "SG", principleId: 16, score: 90, evidence: "Market-driven standards via Enterprise Singapore. International standards adopted. No forced national standards for digital products.", sourceUrl: "https://www.enterprisesg.gov.sg", lastReviewed: "2026-07-29" },
  { countryCode: "SG", principleId: 21, score: 95, evidence: "Strong copyright regime. ISP safe harbor provisions in Copyright Act 2021. Balanced fair use/dealing framework.", sourceUrl: "https://www.ipos.gov.sg", lastReviewed: "2026-07-29" },
  { countryCode: "SG", principleId: 22, score: 90, evidence: "IPOS patent examination. Patent Cooperation Treaty member. Fast-track patent prosecution for AI/tech innovations.", sourceUrl: "https://www.ipos.gov.sg", lastReviewed: "2026-07-29" },
  { countryCode: "SG", principleId: 23, score: 85, evidence: "Trade secret protection under common law and Penal Code. Computer Misuse Act covers cyber theft. No dedicated trade secret statute.", sourceUrl: "https://www.ipos.gov.sg", lastReviewed: "2026-07-29" },
  { countryCode: "SG", principleId: 24, score: 90, evidence: "MRA participation for conformity assessment. SAC-accredited testing labs mutually recognized. ASEAN EE MRA signatory.", sourceUrl: "https://www.enterprisesg.gov.sg", lastReviewed: "2026-07-29" },

  // ══════════════════════════════════════════════════════════════
  // MALAYSIA (MY) — CPTPP Member (Nov 2022), Open Transfer
  // ══════════════════════════════════════════════════════════════
  { countryCode: "MY", principleId: 1, score: 75, evidence: "Generally open internet. Some content blocking under MCMC for 'objectionable' content. Political content filtering concerns.", sourceUrl: "https://www.mcmc.gov.my", lastReviewed: "2026-07-29" },
  { countryCode: "MY", principleId: 11, score: 75, evidence: "Competitive telco market (Maxis, CelcomDigi, U Mobile). Multiple cable landings. Some foreign ownership restrictions remain.", sourceUrl: "https://www.mcmc.gov.my", lastReviewed: "2026-07-29" },
  { countryCode: "MY", principleId: 17, score: 90, evidence: "WTO ITA signatory. Most ICT goods duty-free. MFN tariffs on some electronics remain but being phased out.", sourceUrl: "https://www.customs.gov.my", lastReviewed: "2026-07-29" },
  { countryCode: "MY", principleId: 18, score: 80, evidence: "uCustoms single-window system. E-customs portal operational. Express shipment clearance improving but not fully paperless.", sourceUrl: "https://www.customs.gov.my", lastReviewed: "2026-07-29" },
  { countryCode: "MY", principleId: 2, score: 85, evidence: "No digital customs duties. Service tax on digital services (6%) applies to foreign providers — broad consumption tax, not discriminatory duty.", sourceUrl: "https://www.customs.gov.my", lastReviewed: "2026-07-29" },
  { countryCode: "MY", principleId: 3, score: 75, evidence: "Generally non-discriminatory for foreign digital services. Some sectoral restrictions in financial services and telecommunications.", sourceUrl: "https://www.mcmc.gov.my", lastReviewed: "2026-07-29" },
  { countryCode: "MY", principleId: 4, score: 80, evidence: "PDPA 2010 permits transfers to whitelisted countries and via data transfer agreements. Amendment 2024 strengthens cross-border framework.", sourceUrl: "https://www.pdp.gov.my", lastReviewed: "2026-07-29" },
  { countryCode: "MY", principleId: 5, score: 80, evidence: "No blanket data localization. Sector-specific requirements in banking (BNM outsourcing guidelines). Cloud-first government policy.", sourceUrl: "https://www.pdp.gov.my", lastReviewed: "2026-07-29" },
  { countryCode: "MY", principleId: 13, score: 75, evidence: "CPTPP ratification brings digital trade chapter obligations. DEFA active participant. Slower to adopt standalone DEAs.", sourceUrl: "https://www.miti.gov.my", lastReviewed: "2026-07-29" },
  { countryCode: "MY", principleId: 14, score: 80, evidence: "Generally open to foreign digital services. Cloud providers operate. Some local presence preferences in government procurement.", sourceUrl: "https://www.miti.gov.my", lastReviewed: "2026-07-29" },
  { countryCode: "MY", principleId: 6, score: 70, evidence: "No explicit forced tech transfer laws. Some sectoral policies encourage technology partnerships with local firms for market access.", sourceUrl: "https://www.miti.gov.my", lastReviewed: "2026-07-29" },
  { countryCode: "MY", principleId: 7, score: 65, evidence: "No mandatory source code disclosure. MCMC has authority to request technical information under licensing. CPTPP obligations strengthen protection.", sourceUrl: "https://www.mcmc.gov.my", lastReviewed: "2026-07-29" },
  { countryCode: "MY", principleId: 8, score: 80, evidence: "Technology-neutral licensing. No mandated local technology standards. Market-driven tech adoption across most sectors.", sourceUrl: "https://www.mcmc.gov.my", lastReviewed: "2026-07-29" },
  { countryCode: "MY", principleId: 9, score: 80, evidence: "Digital Signature Act 1997. MyDigital ID national digital identity. Multiple accredited certification authorities.", sourceUrl: "https://www.mcmc.gov.my", lastReviewed: "2026-07-29" },
  { countryCode: "MY", principleId: 12, score: 65, evidence: "No encryption ban. National Cyber Security Agency focuses on CII. No mandatory backdoor requirements. Some encryption product import notification requirements.", sourceUrl: "https://www.nacsa.gov.my", lastReviewed: "2026-07-29" },
  { countryCode: "MY", principleId: 10, score: 75, evidence: "Consumer Protection Act 1999 covers e-commerce. PDPA breach notification required. Tribunal for Consumer Claims accessible online.", sourceUrl: "https://www.kpdn.gov.my", lastReviewed: "2026-07-29" },
  { countryCode: "MY", principleId: 15, score: 75, evidence: "NACSA coordinates cybersecurity. MyCERT incident response. Active in ASEAN cybersecurity cooperation. Capacity building ongoing.", sourceUrl: "https://www.nacsa.gov.my", lastReviewed: "2026-07-29" },
  { countryCode: "MY", principleId: 19, score: 60, evidence: "Public consultations held for major ICT regulations. Limited meaningful civil society engagement. Official Secrets Act constrains transparency.", sourceUrl: "https://www.mcmc.gov.my", lastReviewed: "2026-07-29" },
  { countryCode: "MY", principleId: 20, score: 60, evidence: "Telekom Malaysia government-linked. Khazanah-linked tech companies compete. Some preferential treatment in government procurement.", sourceUrl: "https://www.mcmc.gov.my", lastReviewed: "2026-07-29" },
  { countryCode: "MY", principleId: 16, score: 80, evidence: "SIRIM leads standards development. International standards widely adopted. No forced unique national standards for ICT products.", sourceUrl: "https://www.sirim.my", lastReviewed: "2026-07-29" },
  { countryCode: "MY", principleId: 21, score: 70, evidence: "Copyright Act 1987. ISP liability provisions exist but safe harbors less developed than US/EU models. Ongoing reform discussions.", sourceUrl: "https://www.myipo.gov.my", lastReviewed: "2026-07-29" },
  { countryCode: "MY", principleId: 22, score: 75, evidence: "MyIPO patent examination. PCT member. Patent prosecution highway with Japan. AI patentability guidelines under development.", sourceUrl: "https://www.myipo.gov.my", lastReviewed: "2026-07-29" },
  { countryCode: "MY", principleId: 23, score: 65, evidence: "Trade secret protection under common law. Computer Crimes Act covers unauthorized access. No specific criminal procedures for cyber trade secret theft.", sourceUrl: "https://www.myipo.gov.my", lastReviewed: "2026-07-29" },
  { countryCode: "MY", principleId: 24, score: 75, evidence: "Standards Malaysia accreditation. SAMM-accredited labs. ASEAN EE MRA participation. Mutual recognition improving.", sourceUrl: "https://www.sirim.my", lastReviewed: "2026-07-29" },

  // ══════════════════════════════════════════════════════════════
  // VIETNAM (VN) — CPTPP Member, Strict Localization
  // ══════════════════════════════════════════════════════════════
  { countryCode: "VN", principleId: 1, score: 30, evidence: "Extensive content blocking. Thousands of websites blocked. Social media content removal orders. Decree 147 mandates content takedown within 24 hours.", sourceUrl: "https://vanban.chinhphu.vn", lastReviewed: "2026-07-29" },
  { countryCode: "VN", principleId: 11, score: 45, evidence: "State-owned VNPT and Viettel dominate. Foreign ownership capped at 49%. Submarine cable landings exist but state-controlled.", sourceUrl: "https://mic.gov.vn", lastReviewed: "2026-07-29" },
  { countryCode: "VN", principleId: 17, score: 65, evidence: "WTO ITA participant. ICT tariffs reduced under CPTPP schedule. Some electronics still face import duties during phase-out.", sourceUrl: "https://www.customs.gov.vn", lastReviewed: "2026-07-29" },
  { countryCode: "VN", principleId: 18, score: 55, evidence: "VNACCS/VCIS customs system operational. Paperless improving but manual procedures persist. Express shipment processing slower than Singapore.", sourceUrl: "https://www.customs.gov.vn", lastReviewed: "2026-07-29" },
  { countryCode: "VN", principleId: 2, score: 70, evidence: "No specific digital customs duties. CPTPP prohibition applies. Digital service taxation introduced but structured as VAT, not duty.", sourceUrl: "https://www.gdt.gov.vn", lastReviewed: "2026-07-29" },
  { countryCode: "VN", principleId: 3, score: 40, evidence: "Significant discrimination against foreign digital platforms. Decree 147 mandates local offices. Domestic platforms (Zalo, Cốc Cốc) receive regulatory preference.", sourceUrl: "https://mic.gov.vn", lastReviewed: "2026-07-29" },
  { countryCode: "VN", principleId: 4, score: 20, evidence: "Mandatory onshore data storage under Cybersecurity Law and Decree 53. Local user data must be stored in Vietnam. Foreign transfers heavily restricted.", sourceUrl: "https://vanban.chinhphu.vn", lastReviewed: "2026-07-29" },
  { countryCode: "VN", principleId: 5, score: 15, evidence: "Strict data localization mandates. Foreign tech firms (cloud, social networks, OTT) must store user data in Vietnam and establish local branch offices.", sourceUrl: "https://vanban.chinhphu.vn", lastReviewed: "2026-07-29" },
  { countryCode: "VN", principleId: 13, score: 50, evidence: "CPTPP digital chapter provides framework. DEFA negotiations ongoing. Domestic regulations evolving rapidly, creating uncertainty for foreign firms.", sourceUrl: "https://mic.gov.vn", lastReviewed: "2026-07-29" },
  { countryCode: "VN", principleId: 14, score: 40, evidence: "Foreign digital services restricted. Local office requirements under Decree 147. Cross-border service supply limited for many digital service categories.", sourceUrl: "https://mic.gov.vn", lastReviewed: "2026-07-29" },
  { countryCode: "VN", principleId: 6, score: 25, evidence: "Technology transfer required in some sectors for market access. Investment approvals often conditional on local technology partnerships and transfer.", sourceUrl: "https://www.mpi.gov.vn", lastReviewed: "2026-07-29" },
  { countryCode: "VN", principleId: 7, score: 20, evidence: "Draft AI Law proposes mandatory algorithm audits and source code disclosure. Cybersecurity Law requires technical data provision to authorities on request.", sourceUrl: "https://mic.gov.vn", lastReviewed: "2026-07-29" },
  { countryCode: "VN", principleId: 8, score: 30, evidence: "MIC mandates use of domestic technology standards in some sectors. Telecom equipment type-approval favors local standards. National digital transformation agenda promotes local tech.", sourceUrl: "https://mic.gov.vn", lastReviewed: "2026-07-29" },
  { countryCode: "VN", principleId: 9, score: 55, evidence: "E-transactions Law supports e-signatures. VNPT-CA and other local CAs dominate. Foreign e-signature acceptance limited.", sourceUrl: "https://mic.gov.vn", lastReviewed: "2026-07-29" },
  { countryCode: "VN", principleId: 12, score: 20, evidence: "Encryption products require registration and licensing. Cybersecurity Law requires decryption capability for authorities. VPN restrictions under Decree 53.", sourceUrl: "https://vanban.chinhphu.vn", lastReviewed: "2026-07-29" },
  { countryCode: "VN", principleId: 10, score: 45, evidence: "Consumer protection law exists but enforcement weak. E-commerce consumer rights in Decree 52. Limited enforcement against fraudulent digital services.", sourceUrl: "https://mic.gov.vn", lastReviewed: "2026-07-29" },
  { countryCode: "VN", principleId: 15, score: 45, evidence: "National Cybersecurity Center operational. VNCERT incident response. Participates in ASEAN cybersecurity cooperation but transparency limited.", sourceUrl: "https://mic.gov.vn", lastReviewed: "2026-07-29" },
  { countryCode: "VN", principleId: 19, score: 15, evidence: "Severely limited regulatory transparency. Decree 53 and Cybersecurity Law implementing regulations developed with minimal public consultation. Civil society engagement largely absent.", sourceUrl: "https://mic.gov.vn", lastReviewed: "2026-07-29" },
  { countryCode: "VN", principleId: 20, score: 25, evidence: "SOEs (VNPT, Viettel, Mobifone) dominate telecom. State enterprises receive preferential regulatory treatment, subsidies, and spectrum allocation.", sourceUrl: "https://mic.gov.vn", lastReviewed: "2026-07-29" },
  { countryCode: "VN", principleId: 16, score: 40, evidence: "National standards (TCVN) sometimes deviate from international standards. MIC pushes for domestic technology standards. CPTPP commitments constrain but do not eliminate.", sourceUrl: "https://mic.gov.vn", lastReviewed: "2026-07-29" },
  { countryCode: "VN", principleId: 21, score: 40, evidence: "Copyright law amended 2022. ISP safe harbor provisions weak. Platform liability for user content broad. Enforcement inconsistent and sometimes politically motivated.", sourceUrl: "https://www.cov.gov.vn", lastReviewed: "2026-07-29" },
  { countryCode: "VN", principleId: 22, score: 45, evidence: "Patent system exists. NOIP examination. CPTPP commitments strengthening IP framework. Patent enforcement remains challenging for foreign firms.", sourceUrl: "https://www.noip.gov.vn", lastReviewed: "2026-07-29" },
  { countryCode: "VN", principleId: 23, score: 30, evidence: "Limited criminal procedures for trade secret theft. IP enforcement generally weak. State-linked entities have faced allegations of IP misappropriation.", sourceUrl: "https://www.noip.gov.vn", lastReviewed: "2026-07-29" },
  { countryCode: "VN", principleId: 24, score: 50, evidence: "STAMEQ conformity assessment. MRA participation limited. Foreign testing lab recognition improving but still restricted in some sectors.", sourceUrl: "https://mic.gov.vn", lastReviewed: "2026-07-29" },

  // ══════════════════════════════════════════════════════════════
  // INDONESIA (ID) — Hybrid, CPTPP Applicant
  // ══════════════════════════════════════════════════════════════
  { countryCode: "ID", principleId: 1, score: 45, evidence: "Significant content blocking by Kominfo (800,000+ sites). Pornography, gambling, extremist content blocked. Political content filtering concerns. Social media throttling during unrest.", sourceUrl: "https://www.kominfo.go.id", lastReviewed: "2026-07-29" },
  { countryCode: "ID", principleId: 11, score: 50, evidence: "Telkomsel (state-linked) dominates mobile. Palapa Ring backbone state-funded. Foreign ownership caps. Submarine cable landings exist.", sourceUrl: "https://www.kominfo.go.id", lastReviewed: "2026-07-29" },
  { countryCode: "ID", principleId: 17, score: 65, evidence: "WTO ITA signatory. ICT tariffs being reduced. Local content (TKDN) requirements effectively function as tariff-equivalents for 4G/5G equipment.", sourceUrl: "https://www.kominfo.go.id", lastReviewed: "2026-07-29" },
  { countryCode: "ID", principleId: 18, score: 55, evidence: "INSW single-window system functioning. E-customs improving. Bureaucratic delays persist. Multiple agencies involved in ICT import clearance.", sourceUrl: "https://www.beacukai.go.id", lastReviewed: "2026-07-29" },
  { countryCode: "ID", principleId: 2, score: 65, evidence: "No digital customs duties specifically. VAT on digital services (PPN PMSE) applies to foreign providers at 11%. Broad consumption tax, not discriminatory.", sourceUrl: "https://www.pajak.go.id", lastReviewed: "2026-07-29" },
  { countryCode: "ID", principleId: 3, score: 45, evidence: "TKDN requirements favor local products. MR5 mandates 24-hour content removal — discriminatorily burdens foreign platforms. Domestic platform preferences in government procurement.", sourceUrl: "https://www.kominfo.go.id", lastReviewed: "2026-07-29" },
  { countryCode: "ID", principleId: 4, score: 40, evidence: "PDP Law No. 27/2022 requires adequacy determination for data exports. Public sector data must be stored domestically (PP 71/2019). Private sector has contractual options but regulatory uncertainty persists.", sourceUrl: "https://www.kominfo.go.id", lastReviewed: "2026-07-29" },
  { countryCode: "ID", principleId: 5, score: 35, evidence: "Public electronic system operators (PSE) must store data domestically. GR 71 mandates government data localization. Private PSE scope expanding under MR5.", sourceUrl: "https://www.kominfo.go.id", lastReviewed: "2026-07-29" },
  { countryCode: "ID", principleId: 13, score: 50, evidence: "CPTPP accession applied. DEFA active negotiator. Domestic regulatory environment volatile — GR 71, MR5, PDP Law create uncertain framework.", sourceUrl: "https://www.kominfo.go.id", lastReviewed: "2026-07-29" },
  { countryCode: "ID", principleId: 14, score: 45, evidence: "PSE registration requirement for all electronic system operators. Foreign cloud providers must register. Cross-border digital services restricted for public sector.", sourceUrl: "https://www.kominfo.go.id", lastReviewed: "2026-07-29" },
  { countryCode: "ID", principleId: 6, score: 30, evidence: "TKDN (local content) requirements effectively force technology transfer for telecom equipment. 35%+ local content for 4G/5G base stations. Investment conditional on local partnerships.", sourceUrl: "https://www.kominfo.go.id", lastReviewed: "2026-07-29" },
  { countryCode: "ID", principleId: 7, score: 30, evidence: "MR5 requires audit access to algorithms for private PSE. Kominfo can request technical systems information. Draft AI regulation proposes mandatory algorithmic transparency.", sourceUrl: "https://www.kominfo.go.id", lastReviewed: "2026-07-29" },
  { countryCode: "ID", principleId: 8, score: 35, evidence: "TKDN mandates use of local components in telecom equipment. SNI (national standards) can deviate from international standards. Technology choice constrained by local content mandates.", sourceUrl: "https://www.kominfo.go.id", lastReviewed: "2026-07-29" },
  { countryCode: "ID", principleId: 9, score: 60, evidence: "E-signatures recognized under ITE Law. BSrE provides government certification. Foreign e-signatures face acceptance challenges.", sourceUrl: "https://www.kominfo.go.id", lastReviewed: "2026-07-29" },
  { countryCode: "ID", principleId: 12, score: 45, evidence: "No explicit encryption ban. BSSN focuses on national cryptography standards. Some encryption product registration requirements. VPNs generally permitted but monitored.", sourceUrl: "https://www.bssn.go.id", lastReviewed: "2026-07-29" },
  { countryCode: "ID", principleId: 10, score: 50, evidence: "Consumer Protection Law exists. E-commerce consumer rights under PP 80/2019. Breach notification under PDP Law. Enforcement capacity limited outside Java.", sourceUrl: "https://www.kominfo.go.id", lastReviewed: "2026-07-29" },
  { countryCode: "ID", principleId: 15, score: 55, evidence: "BSSN established. Id-SIRTII incident response. Active in ASEAN cybersecurity cooperation. Capacity building ongoing but under-resourced.", sourceUrl: "https://www.bssn.go.id", lastReviewed: "2026-07-29" },
  { countryCode: "ID", principleId: 19, score: 35, evidence: "Limited public consultation on digital regulations. MR5 developed with minimal transparency. Civil society engagement limited. Business consultation channels exist but effectiveness varies.", sourceUrl: "https://www.kominfo.go.id", lastReviewed: "2026-07-29" },
  { countryCode: "ID", principleId: 20, score: 35, evidence: "SOEs (Telkom Indonesia, Telkomsel) dominate telecom with regulatory advantages. Spectrum allocation favors incumbents. State-owned enterprises receive preferential government procurement access.", sourceUrl: "https://www.kominfo.go.id", lastReviewed: "2026-07-29" },
  { countryCode: "ID", principleId: 16, score: 45, evidence: "SNI standards sometimes mandatory and deviate from international norms. BSN leads standards development. Industry input exists but government-driven.", sourceUrl: "https://www.bsn.go.id", lastReviewed: "2026-07-29" },
  { countryCode: "ID", principleId: 21, score: 45, evidence: "Copyright Law No. 28/2014. ISP liability provisions exist. Notice-and-takedown mechanism present but criticized for overcompliance and chilling effects.", sourceUrl: "https://www.dgip.go.id", lastReviewed: "2026-07-29" },
  { countryCode: "ID", principleId: 22, score: 50, evidence: "DGIP patent examination. PCT member. Patent prosecution improving but backlog remains significant. Simple patent system for local innovations.", sourceUrl: "https://www.dgip.go.id", lastReviewed: "2026-07-29" },
  { countryCode: "ID", principleId: 23, score: 35, evidence: "Trade secret protection under Law No. 30/2000. Criminal provisions exist but enforcement weak. No specific cyber trade secret theft framework.", sourceUrl: "https://www.dgip.go.id", lastReviewed: "2026-07-29" },
  { countryCode: "ID", principleId: 24, score: 55, evidence: "KAN accreditation body. Testing labs exist. ASEAN MRA participation. Foreign conformity assessment body recognition improving but limitations persist.", sourceUrl: "https://www.bsn.go.id", lastReviewed: "2026-07-29" },

  // ══════════════════════════════════════════════════════════════
  // THAILAND (TH) — Hybrid, CPTPP Expressed Interest
  // ══════════════════════════════════════════════════════════════
  { countryCode: "TH", principleId: 1, score: 50, evidence: "Lèse-majesté content blocked extensively. Political content filtering during unrest. Social media blocking orders under Computer Crime Act. VPN usage widespread to bypass blocks.", sourceUrl: "https://www.etda.or.th", lastReviewed: "2026-07-29" },
  { countryCode: "TH", principleId: 11, score: 65, evidence: "Competitive mobile market (AIS, True, dtac). Multiple submarine cable landings. Foreign ownership restrictions in telecom but manageable.", sourceUrl: "https://www.nbtc.go.th", lastReviewed: "2026-07-29" },
  { countryCode: "TH", principleId: 17, score: 75, evidence: "WTO ITA signatory. Most ICT goods duty-free. Some electronics tariffs being reduced. Automotive electronics sector liberalized.", sourceUrl: "https://www.customs.go.th", lastReviewed: "2026-07-29" },
  { countryCode: "TH", principleId: 18, score: 65, evidence: "e-Customs system operational. NSW single window improving. Express shipment processing available but documentation requirements still heavy.", sourceUrl: "https://www.customs.go.th", lastReviewed: "2026-07-29" },
  { countryCode: "TH", principleId: 2, score: 75, evidence: "No digital customs duties. VAT on digital services (7%) applies equally to foreign and domestic providers. WTO moratorium supporter.", sourceUrl: "https://www.rd.go.th", lastReviewed: "2026-07-29" },
  { countryCode: "TH", principleId: 3, score: 60, evidence: "Generally non-discriminatory for registered digital services. Foreign platforms facing increasing regulatory scrutiny. Platform operator licensing requirements under Royal Decree.", sourceUrl: "https://www.etda.or.th", lastReviewed: "2026-07-29" },
  { countryCode: "TH", principleId: 4, score: 60, evidence: "PDPA B.E. 2562 permits transfers to adequate countries or via SCCs. Adequacy list limited. Cross-border transfer framework GDPR-inspired but implementation ongoing.", sourceUrl: "https://www.pdpc.or.th", lastReviewed: "2026-07-29" },
  { countryCode: "TH", principleId: 5, score: 65, evidence: "No blanket data localization. PDPC can impose sectoral localization under adequacy assessments. Generally open framework with safeguards.", sourceUrl: "https://www.pdpc.or.th", lastReviewed: "2026-07-29" },
  { countryCode: "TH", principleId: 13, score: 55, evidence: "CPTPP interest expressed but no accession. DEFA active participant. Digital platform regulation evolving — Royal Decree on Digital Platforms creates new obligations.", sourceUrl: "https://www.etda.or.th", lastReviewed: "2026-07-29" },
  { countryCode: "TH", principleId: 14, score: 60, evidence: "Foreign digital service providers can operate. Platform operator registration required above thresholds. No blanket market access restrictions but regulatory compliance burden growing.", sourceUrl: "https://www.etda.or.th", lastReviewed: "2026-07-29" },
  { countryCode: "TH", principleId: 6, score: 55, evidence: "BOI investment promotion sometimes encourages technology partnerships. No explicit forced transfer laws but practice in some sectors. CPTPP accession would strengthen protections.", sourceUrl: "https://www.boi.go.th", lastReviewed: "2026-07-29" },
  { countryCode: "TH", principleId: 7, score: 55, evidence: "No mandatory source code disclosure generally. ETDA algorithmic audit requirement for large platforms (5M+ users) raises transparency concerns. Scope of audit not yet fully defined.", sourceUrl: "https://www.etda.or.th", lastReviewed: "2026-07-29" },
  { countryCode: "TH", principleId: 8, score: 70, evidence: "Generally technology-neutral regulations. NBTC type-approval uses international standards. No forced local technology mandates for most sectors.", sourceUrl: "https://www.nbtc.go.th", lastReviewed: "2026-07-29" },
  { countryCode: "TH", principleId: 9, score: 75, evidence: "Electronic Transactions Act supports e-signatures. ThaiD national digital ID. Multiple certified e-signature providers. Growing adoption.", sourceUrl: "https://www.etda.or.th", lastReviewed: "2026-07-29" },
  { countryCode: "TH", principleId: 12, score: 55, evidence: "No encryption ban. Computer Crime Act powers can be used to compel decryption in investigations. No mandatory backdoor but law enforcement access framework exists.", sourceUrl: "https://www.etda.or.th", lastReviewed: "2026-07-29" },
  { countryCode: "TH", principleId: 10, score: 65, evidence: "Consumer Protection Act covers digital transactions. PDPA breach notification mandated. OCPB handles complaints. Growing enforcement but capacity constraints.", sourceUrl: "https://www.ocpb.go.th", lastReviewed: "2026-07-29" },
  { countryCode: "TH", principleId: 15, score: 65, evidence: "NCSC coordinates cybersecurity. ThaiCERT incident response. Active in ASEAN cybersecurity cooperation. National Cybersecurity Act provides framework.", sourceUrl: "https://www.ncsa.or.th", lastReviewed: "2026-07-29" },
  { countryCode: "TH", principleId: 19, score: 40, evidence: "Limited public consultation on digital laws. Computer Crime Act amendments rushed. ETDA holds some stakeholder forums but civil society participation restricted.", sourceUrl: "https://www.etda.or.th", lastReviewed: "2026-07-29" },
  { countryCode: "TH", principleId: 20, score: 45, evidence: "State enterprises (CAT, TOT) historically dominated — now merged into NT. Privatization ongoing. Some SOE advantages remain in spectrum and government contracts.", sourceUrl: "https://www.nbtc.go.th", lastReviewed: "2026-07-29" },
  { countryCode: "TH", principleId: 16, score: 65, evidence: "TISI leads standards development. International standards widely adopted. Some mandatory Thai Industrial Standards for specific products.", sourceUrl: "https://www.tisi.go.th", lastReviewed: "2026-07-29" },
  { countryCode: "TH", principleId: 21, score: 55, evidence: "Copyright Act amended. ISP safe harbor provisions exist but limited compared to DMCA. Platform liability concerns under Computer Crime Act.", sourceUrl: "https://www.ipthailand.go.th", lastReviewed: "2026-07-29" },
  { countryCode: "TH", principleId: 22, score: 60, evidence: "DIP patent examination. PCT member. ASEAN Patent Examination Cooperation. Reasonable examination timelines for digital innovations.", sourceUrl: "https://www.ipthailand.go.th", lastReviewed: "2026-07-29" },
  { countryCode: "TH", principleId: 23, score: 45, evidence: "Trade Secrets Act B.E. 2545 provides civil remedies. Criminal provisions exist in Penal Code. Enforcement limited. No specialized cyber trade secret theft framework.", sourceUrl: "https://www.ipthailand.go.th", lastReviewed: "2026-07-29" },
  { countryCode: "TH", principleId: 24, score: 65, evidence: "TISI/NSC accredited testing labs. MRA participation. ASEAN EE MRA. Foreign conformity assessment recognition improving.", sourceUrl: "https://www.tisi.go.th", lastReviewed: "2026-07-29" },

  // ══════════════════════════════════════════════════════════════
  // PHILIPPINES (PH) — Open Transfer, CPTPP Applicant
  // ══════════════════════════════════════════════════════════════
  { countryCode: "PH", principleId: 1, score: 70, evidence: "Generally open internet. No systematic content blocking. Some site blocking for child sexual abuse material. Political speech generally unrestricted online.", sourceUrl: "https://www.dict.gov.ph", lastReviewed: "2026-07-29" },
  { countryCode: "PH", principleId: 11, score: 65, evidence: "Competitive telco market (Globe, Smart, DITO). Foreign ownership now up to 100% under Public Service Act amendment. Submarine cable landings exist.", sourceUrl: "https://www.dict.gov.ph", lastReviewed: "2026-07-29" },
  { countryCode: "PH", principleId: 17, score: 75, evidence: "WTO ITA signatory. Most ICT goods duty-free. Semiconductor and electronics exports benefit from zero tariffs.", sourceUrl: "https://customs.gov.ph", lastReviewed: "2026-07-29" },
  { countryCode: "PH", principleId: 18, score: 60, evidence: "E2M customs system operational. NSW framework exists. Bureaucratic inefficiencies persist. Express shipment processing improving.", sourceUrl: "https://customs.gov.ph", lastReviewed: "2026-07-29" },
  { countryCode: "PH", principleId: 2, score: 80, evidence: "No digital customs duties. VAT on digital services (12%) applies to foreign providers equally. Broad consumption tax approach.", sourceUrl: "https://www.bir.gov.ph", lastReviewed: "2026-07-29" },
  { countryCode: "PH", principleId: 3, score: 75, evidence: "Generally non-discriminatory for foreign digital services. Foreign platforms operate freely. No local incorporation requirements for most digital services.", sourceUrl: "https://www.dict.gov.ph", lastReviewed: "2026-07-29" },
  { countryCode: "PH", principleId: 4, score: 80, evidence: "Data Privacy Act (RA 10173) permits transfers with accountability. APEC CBPR certified. NPC provides subcontractor accountability framework.", sourceUrl: "https://www.privacy.gov.ph", lastReviewed: "2026-07-29" },
  { countryCode: "PH", principleId: 5, score: 85, evidence: "No data localization requirements. Strong API economy (BPO/IT sector). NPC actively opposes localization barriers. Cloud providers operate freely.", sourceUrl: "https://www.privacy.gov.ph", lastReviewed: "2026-07-29" },
  { countryCode: "PH", principleId: 13, score: 65, evidence: "CPTPP accession applied. DEFA host of 57th SEOM (May 2026). Digital economy legislation evolving — E-Governance Act, E-Commerce Act amendments.", sourceUrl: "https://www.dti.gov.ph", lastReviewed: "2026-07-29" },
  { countryCode: "PH", principleId: 14, score: 75, evidence: "Open to foreign digital services. BPO/IT sector demonstrates service access. Cloud providers operate. Some profession licensing restrictions for digital services.", sourceUrl: "https://www.dti.gov.ph", lastReviewed: "2026-07-29" },
  { countryCode: "PH", principleId: 6, score: 65, evidence: "No explicit forced tech transfer laws. Investment incentives sometimes encourage local partnerships. Technology transfer agreements must be registered with IPO.", sourceUrl: "https://www.boi.gov.ph", lastReviewed: "2026-07-29" },
  { countryCode: "PH", principleId: 7, score: 65, evidence: "No mandatory source code disclosure. NPC can request technical information in data breach investigations. Generally protective of proprietary software.", sourceUrl: "https://www.privacy.gov.ph", lastReviewed: "2026-07-29" },
  { countryCode: "PH", principleId: 8, score: 80, evidence: "Technology-neutral regulations. NTC type-approval uses international standards. No mandated local technology for digital products.", sourceUrl: "https://www.dict.gov.ph", lastReviewed: "2026-07-29" },
  { countryCode: "PH", principleId: 9, score: 75, evidence: "E-Commerce Act recognizes e-signatures. PhilID national digital identity. Multiple certification authorities. Growing digital ID adoption.", sourceUrl: "https://www.dict.gov.ph", lastReviewed: "2026-07-29" },
  { countryCode: "PH", principleId: 12, score: 65, evidence: "No encryption ban. Cybercrime Prevention Act focuses on illegal access. No mandatory backdoor requirements. Strong encryption products freely available.", sourceUrl: "https://www.dict.gov.ph", lastReviewed: "2026-07-29" },
  { countryCode: "PH", principleId: 10, score: 70, evidence: "Consumer Act of the Philippines covers e-commerce. DPA breach notification required. DTI handles online complaints. Enforcement improving but capacity varies.", sourceUrl: "https://www.dti.gov.ph", lastReviewed: "2026-07-29" },
  { countryCode: "PH", principleId: 15, score: 65, evidence: "DICT and CICC coordinate cybersecurity. CERT-PH incident response. Active in ASEAN cybersecurity cooperation. Capacity building ongoing.", sourceUrl: "https://www.dict.gov.ph", lastReviewed: "2026-07-29" },
  { countryCode: "PH", principleId: 19, score: 55, evidence: "Public consultations held for major digital laws. NPC conducts stakeholder engagement. Congressional process allows some input but transparency limited on executive regulations.", sourceUrl: "https://www.dict.gov.ph", lastReviewed: "2026-07-29" },
  { countryCode: "PH", principleId: 20, score: 55, evidence: "PLDT historically dominant. Privatization largely complete but regulatory advantages persist. Government procurement preferences for local firms.", sourceUrl: "https://www.ntc.gov.ph", lastReviewed: "2026-07-29" },
  { countryCode: "PH", principleId: 16, score: 75, evidence: "BPS leads standards development. International standards widely adopted. No forced unique national standards for most ICT products.", sourceUrl: "https://www.dti.gov.ph", lastReviewed: "2026-07-29" },
  { countryCode: "PH", principleId: 21, score: 60, evidence: "IP Code (RA 8293). ISP liability provisions exist. Copyright enforcement improving but piracy still significant. DMCA-style safe harbors not fully implemented.", sourceUrl: "https://www.ipophil.gov.ph", lastReviewed: "2026-07-29" },
  { countryCode: "PH", principleId: 22, score: 60, evidence: "IPOPHL patent examination. PCT member. ASEAN Patent Examination Cooperation. Reasonable timelines. Backlog being addressed.", sourceUrl: "https://www.ipophil.gov.ph", lastReviewed: "2026-07-29" },
  { countryCode: "PH", principleId: 23, score: 50, evidence: "Trade secret protection under IP Code and Civil Code. Cybercrime Prevention Act covers unauthorized access. Enforcement moderate but improving.", sourceUrl: "https://www.ipophil.gov.ph", lastReviewed: "2026-07-29" },
  { countryCode: "PH", principleId: 24, score: 65, evidence: "PAO accreditation body. Testing labs accredited. MRA participation. ASEAN EE MRA signatory. Recognition improving.", sourceUrl: "https://www.dti.gov.ph", lastReviewed: "2026-07-29" },

  // ══════════════════════════════════════════════════════════════
  // MYANMAR (MM) — Strict Localization, Military Regime
  // ══════════════════════════════════════════════════════════════
  { countryCode: "MM", principleId: 1, score: 10, evidence: "Frequent internet shutdowns. Military junta blocks social media platforms routinely. 2021 coup triggered near-total blackout. VPN usage criminalized under draft law.", sourceUrl: "https://www.accessnow.org", lastReviewed: "2026-07-29" },
  { countryCode: "MM", principleId: 11, score: 15, evidence: "State-controlled MPT dominates. Military controls telecommunications infrastructure. Submarine cable landing under military supervision. Foreign investment largely withdrawn.", sourceUrl: "https://www.motc.gov.mm", lastReviewed: "2026-07-29" },
  { countryCode: "MM", principleId: 17, score: 30, evidence: "Not WTO ITA signatory. Tariffs on ICT products remain high. Sanctions complicate trade. Limited transparency on tariff schedules.", sourceUrl: "https://www.motc.gov.mm", lastReviewed: "2026-07-29" },
  { countryCode: "MM", principleId: 18, score: 15, evidence: "Customs procedures severely disrupted post-coup. Electronic systems non-functional or restricted. Manual processing creates extreme delays and corruption risks.", sourceUrl: "https://www.motc.gov.mm", lastReviewed: "2026-07-29" },
  { countryCode: "MM", principleId: 2, score: 30, evidence: "No specific digital customs duties regime. Import restrictions on ICT equipment effectively function as non-tariff barriers. Sanctions complicate digital trade.", sourceUrl: "https://www.motc.gov.mm", lastReviewed: "2026-07-29" },
  { countryCode: "MM", principleId: 3, score: 10, evidence: "Severe discrimination against foreign digital platforms. Military-controlled domestic alternatives only. Foreign social media routinely blocked. Foreign firms face extortionate licensing.", sourceUrl: "https://www.motc.gov.mm", lastReviewed: "2026-07-29" },
  { countryCode: "MM", principleId: 4, score: 5, evidence: "Data cannot freely flow. Military controls all telecommunications. Draft Cybersecurity Law mandates data localization and state access. No legal cross-border data transfer framework.", sourceUrl: "https://www.motc.gov.mm", lastReviewed: "2026-07-29" },
  { countryCode: "MM", principleId: 5, score: 5, evidence: "Extreme de facto localization — military controls all digital infrastructure. Foreign data centers impossible to operate. All data routed through state-controlled gateways.", sourceUrl: "https://www.motc.gov.mm", lastReviewed: "2026-07-29" },
  { countryCode: "MM", principleId: 13, score: 10, evidence: "No participation in modern digital trade frameworks. DEFA membership frozen. All CPTPP/DEPA access impossible under military rule. Digital isolation deepening.", sourceUrl: "https://www.motc.gov.mm", lastReviewed: "2026-07-29" },
  { countryCode: "MM", principleId: 14, score: 5, evidence: "Foreign digital services effectively banned. Military junta controls all electronic communications. Foreign tech companies have withdrawn or suspended operations.", sourceUrl: "https://www.motc.gov.mm", lastReviewed: "2026-07-29" },
  { countryCode: "MM", principleId: 6, score: 5, evidence: "De facto forced technology confiscation. Military expropriation of telecom infrastructure from foreign investors. No legal protection for proprietary technology.", sourceUrl: "https://www.motc.gov.mm", lastReviewed: "2026-07-29" },
  { countryCode: "MM", principleId: 7, score: 5, evidence: "Draft Cybersecurity Law requires source code access and technical data provision to military authorities. Warrantless access to telecommunication logs. No source code protection whatsoever.", sourceUrl: "https://www.motc.gov.mm", lastReviewed: "2026-07-29" },
  { countryCode: "MM", principleId: 8, score: 10, evidence: "No technology choice. Military dictates all technology standards. Foreign technology imports restricted. Military-controlled domestic alternatives mandated.", sourceUrl: "https://www.motc.gov.mm", lastReviewed: "2026-07-29" },
  { countryCode: "MM", principleId: 9, score: 15, evidence: "E-signature infrastructure non-existent. Digital identity systems defunct post-coup. No functioning authentication framework. Cash-based economy dominates.", sourceUrl: "https://www.motc.gov.mm", lastReviewed: "2026-07-29" },
  { countryCode: "MM", principleId: 12, score: 5, evidence: "VPN usage criminalized under draft Cybersecurity Law. Encryption products require military administrative clearance. No legal encryption innovation possible. ISP packet inspection mandated.", sourceUrl: "https://www.motc.gov.mm", lastReviewed: "2026-07-29" },
  { countryCode: "MM", principleId: 10, score: 10, evidence: "No functional consumer protection for digital services. Military rule provides no legal recourse. Digital transactions unsafe and unregulated.", sourceUrl: "https://www.motc.gov.mm", lastReviewed: "2026-07-29" },
  { countryCode: "MM", principleId: 15, score: 10, evidence: "No legitimate cybersecurity cooperation. Military cyber operations focus on surveillance, not protection. International cybersecurity cooperation severed post-coup.", sourceUrl: "https://www.motc.gov.mm", lastReviewed: "2026-07-29" },
  { countryCode: "MM", principleId: 19, score: 5, evidence: "Zero regulatory transparency. All digital regulations issued by military fiat with no consultation. Civil society engagement impossible and dangerous.", sourceUrl: "https://www.motc.gov.mm", lastReviewed: "2026-07-29" },
  { countryCode: "MM", principleId: 20, score: 5, evidence: "Military-owned enterprises control all telecommunications. No private competition. Economy dominated by military-controlled SOEs with no commercial basis.", sourceUrl: "https://www.motc.gov.mm", lastReviewed: "2026-07-29" },
  { countryCode: "MM", principleId: 16, score: 10, evidence: "No market-driven standards process. All standards dictated by military authorities. International standards irrelevant to domestic market.", sourceUrl: "https://www.motc.gov.mm", lastReviewed: "2026-07-29" },
  { countryCode: "MM", principleId: 21, score: 10, evidence: "Copyright law exists on paper but unenforced. Military junta disregards IP protections. Foreign copyright holders have no recourse. No ISP safe harbors.", sourceUrl: "https://www.motc.gov.mm", lastReviewed: "2026-07-29" },
  { countryCode: "MM", principleId: 22, score: 15, evidence: "Patent system defunct. IPO operations disrupted post-coup. No meaningful patent protection for any innovation, domestic or foreign.", sourceUrl: "https://www.motc.gov.mm", lastReviewed: "2026-07-29" },
  { countryCode: "MM", principleId: 23, score: 5, evidence: "No trade secret protection. Military expropriation common. Cyber trade secret theft by state entities unchecked. No criminal procedures or penalties.", sourceUrl: "https://www.motc.gov.mm", lastReviewed: "2026-07-29" },
  { countryCode: "MM", principleId: 24, score: 10, evidence: "No functioning conformity assessment system. International testing and certification not recognized. Products must meet opaque military standards.", sourceUrl: "https://www.motc.gov.mm", lastReviewed: "2026-07-29" },

  // ══════════════════════════════════════════════════════════════
  // CAMBODIA (KH) — Hybrid, National Internet Gateway
  // ══════════════════════════════════════════════════════════════
  { countryCode: "KH", principleId: 1, score: 30, evidence: "NIG sub-decree centralizes internet traffic. Content blocking increasing. Political dissent suppressed online. No explicit internet shutdowns but gateway enables filtering.", sourceUrl: "https://www.mptc.gov.kh", lastReviewed: "2026-07-29" },
  { countryCode: "KH", principleId: 11, score: 35, evidence: "NIG centralizes all international traffic through state-controlled gateway. Limited competition. Foreign telecom investment restricted.", sourceUrl: "https://www.mptc.gov.kh", lastReviewed: "2026-07-29" },
  { countryCode: "KH", principleId: 17, score: 50, evidence: "WTO member. ICT tariffs exist but being reduced. ASEAN harmonization improving but remaining duties on electronics.", sourceUrl: "https://www.mptc.gov.kh", lastReviewed: "2026-07-29" },
  { countryCode: "KH", principleId: 18, score: 40, evidence: "ASYCUDA customs system operational. E-customs developing but manual processes dominate. Express shipment clearance slow.", sourceUrl: "https://www.mptc.gov.kh", lastReviewed: "2026-07-29" },
  { countryCode: "KH", principleId: 2, score: 55, evidence: "No specific digital customs duties. VAT applies to digital services. WTO moratorium supported.", sourceUrl: "https://www.mptc.gov.kh", lastReviewed: "2026-07-29" },
  { countryCode: "KH", principleId: 3, score: 35, evidence: "NIG creates structural discrimination against foreign traffic. Local tech firms receive regulatory preference. Foreign platforms face uncertain regulatory environment.", sourceUrl: "https://www.mptc.gov.kh", lastReviewed: "2026-07-29" },
  { countryCode: "KH", principleId: 4, score: 25, evidence: "NIG routes all international data through state gateway — de facto restriction on data flows. No clear cross-border data transfer framework. Draft e-commerce law addresses data minimally.", sourceUrl: "https://www.mptc.gov.kh", lastReviewed: "2026-07-29" },
  { countryCode: "KH", principleId: 5, score: 25, evidence: "NIG sub-decree mandates local domain storage. NIG routing centralizes all traffic domestically. De facto localization through gateway architecture.", sourceUrl: "https://www.mptc.gov.kh", lastReviewed: "2026-07-29" },
  { countryCode: "KH", principleId: 13, score: 30, evidence: "DEFA participating but capacity limited. Receiving technical assistance for DEFA compliance. Digital legal framework underdeveloped — not adaptable for emerging technologies.", sourceUrl: "https://www.mptc.gov.kh", lastReviewed: "2026-07-29" },
  { countryCode: "KH", principleId: 14, score: 35, evidence: "Foreign digital services operate but under NIG oversight. Service registration requirements emerging. Cross-border digital services subject to gateway monitoring.", sourceUrl: "https://www.mptc.gov.kh", lastReviewed: "2026-07-29" },
  { countryCode: "KH", principleId: 6, score: 40, evidence: "No explicit forced tech transfer laws. Limited investment requiring technology partnerships. Regulatory framework underdeveloped — risks exist but not systematically enforced.", sourceUrl: "https://www.mptc.gov.kh", lastReviewed: "2026-07-29" },
  { countryCode: "KH", principleId: 7, score: 35, evidence: "No clear source code protection framework. NIG architecture enables traffic inspection. Draft cybercrime law may expand government access to technical systems.", sourceUrl: "https://www.mptc.gov.kh", lastReviewed: "2026-07-29" },
  { countryCode: "KH", principleId: 8, score: 40, evidence: "NIG mandates specific routing technology. Limited technology choice in telecom infrastructure. Market-driven adoption constrained by state gateway requirements.", sourceUrl: "https://www.mptc.gov.kh", lastReviewed: "2026-07-29" },
  { countryCode: "KH", principleId: 9, score: 40, evidence: "E-signature legal framework exists but implementation limited. No national digital ID system deployed. Authentication infrastructure nascent.", sourceUrl: "https://www.mptc.gov.kh", lastReviewed: "2026-07-29" },
  { countryCode: "KH", principleId: 12, score: 35, evidence: "No encryption ban but NIG enables traffic monitoring. VPNs available but regulatory uncertainty. No clear encryption product innovation framework.", sourceUrl: "https://www.mptc.gov.kh", lastReviewed: "2026-07-29" },
  { countryCode: "KH", principleId: 10, score: 30, evidence: "Consumer protection law covers e-commerce in principle but enforcement minimal. No specialized digital consumer protection agency. Limited redress mechanisms.", sourceUrl: "https://www.mptc.gov.kh", lastReviewed: "2026-07-29" },
  { countryCode: "KH", principleId: 15, score: 25, evidence: "Limited cybersecurity capacity. No dedicated CERT. Receives ASEAN technical assistance. Cybersecurity focus on surveillance, not protection.", sourceUrl: "https://www.mptc.gov.kh", lastReviewed: "2026-07-29" },
  { countryCode: "KH", principleId: 19, score: 15, evidence: "Minimal regulatory transparency. Laws developed with limited consultation. Civil society engagement constrained. International pressure drives some openness.", sourceUrl: "https://www.mptc.gov.kh", lastReviewed: "2026-07-29" },
  { countryCode: "KH", principleId: 20, score: 30, evidence: "State-linked telecoms dominate. Limited private competition. Government procurement preferences for connected firms.", sourceUrl: "https://www.mptc.gov.kh", lastReviewed: "2026-07-29" },
  { countryCode: "KH", principleId: 16, score: 35, evidence: "Standards development capacity limited. International standards adopted inconsistently. No forced unique national standards but framework underdeveloped.", sourceUrl: "https://www.mptc.gov.kh", lastReviewed: "2026-07-29" },
  { countryCode: "KH", principleId: 21, score: 25, evidence: "Copyright law exists but enforcement extremely weak. No ISP safe harbor provisions. Piracy rampant. IP enforcement capacity minimal.", sourceUrl: "https://www.mptc.gov.kh", lastReviewed: "2026-07-29" },
  { countryCode: "KH", principleId: 22, score: 30, evidence: "Patent system exists on paper but under-resourced. PCT member but limited examination capacity. Digital innovation patents rarely pursued domestically.", sourceUrl: "https://www.mptc.gov.kh", lastReviewed: "2026-07-29" },
  { countryCode: "KH", principleId: 23, score: 20, evidence: "Minimal trade secret protection. No criminal framework for cyber trade secret theft. IP enforcement generally absent.", sourceUrl: "https://www.mptc.gov.kh", lastReviewed: "2026-07-29" },
  { countryCode: "KH", principleId: 24, score: 30, evidence: "Conformity assessment framework developing. Limited accredited testing labs. Foreign certification recognition minimal. ISC standards under development.", sourceUrl: "https://www.mptc.gov.kh", lastReviewed: "2026-07-29" },

  // ══════════════════════════════════════════════════════════════
  // LAOS (LA) — Hybrid, Developing Framework
  // ══════════════════════════════════════════════════════════════
  { countryCode: "LA", principleId: 1, score: 40, evidence: "Internet access generally available but state-monitored. Content blocking occurs for political dissent. Government exercises control over online speech.", sourceUrl: "https://www.mpt.gov.la", lastReviewed: "2026-07-29" },
  { countryCode: "LA", principleId: 11, score: 35, evidence: "State-owned Lao Telecom dominates. Limited competition. Landlocked — relies on neighboring countries for international connectivity. Infrastructure developing.", sourceUrl: "https://www.mpt.gov.la", lastReviewed: "2026-07-29" },
  { countryCode: "LA", principleId: 17, score: 50, evidence: "WTO accession 2013. ICT tariffs exist but being reduced under ASEAN framework. Limited domestic ICT manufacturing.", sourceUrl: "https://www.mpt.gov.la", lastReviewed: "2026-07-29" },
  { countryCode: "LA", principleId: 18, score: 35, evidence: "ASYCUDA implemented. E-customs developing. Manual processing prevalent. Landlocked geography complicates express shipments.", sourceUrl: "https://www.mpt.gov.la", lastReviewed: "2026-07-29" },
  { countryCode: "LA", principleId: 2, score: 55, evidence: "No digital customs duties specifically. Limited digital economy means low relevance. VAT framework developing.", sourceUrl: "https://www.mpt.gov.la", lastReviewed: "2026-07-29" },
  { countryCode: "LA", principleId: 3, score: 40, evidence: "State-linked digital platforms receive preference. Foreign platforms operate but face regulatory uncertainty. Limited formal discrimination but structural barriers exist.", sourceUrl: "https://www.mpt.gov.la", lastReviewed: "2026-07-29" },
  { countryCode: "LA", principleId: 4, score: 30, evidence: "Draft data protection law under development. No current cross-border data transfer framework. Data flows governed by ad hoc arrangements.", sourceUrl: "https://www.mpt.gov.la", lastReviewed: "2026-07-29" },
  { countryCode: "LA", principleId: 5, score: 40, evidence: "No explicit data localization requirements. Limited digital infrastructure means data often stored domestically by default. Framework underdeveloped.", sourceUrl: "https://www.mpt.gov.la", lastReviewed: "2026-07-29" },
  { countryCode: "LA", principleId: 13, score: 30, evidence: "DEFA participating but capacity limited. ASEAN Digital Masterplan 2025 alignment ongoing. Digital legal framework nascent — significant gaps.", sourceUrl: "https://www.mpt.gov.la", lastReviewed: "2026-07-29" },
  { countryCode: "LA", principleId: 14, score: 40, evidence: "Foreign digital services operate with minimal regulation. Limited market for premium digital services. Cross-border services framework undeveloped.", sourceUrl: "https://www.mpt.gov.la", lastReviewed: "2026-07-29" },
  { countryCode: "LA", principleId: 6, score: 45, evidence: "No explicit forced tech transfer laws. Limited tech sector investment means low incidence. Framework underdeveloped but not actively hostile.", sourceUrl: "https://www.mpt.gov.la", lastReviewed: "2026-07-29" },
  { countryCode: "LA", principleId: 7, score: 40, evidence: "No source code disclosure requirements. Cybercrime law grants investigative powers that could extend to technical data. Framework ambiguous.", sourceUrl: "https://www.mpt.gov.la", lastReviewed: "2026-07-29" },
  { countryCode: "LA", principleId: 8, score: 45, evidence: "Technology standards developing. No mandatory local technology requirements. Limited domestic tech industry means international standards dominate.", sourceUrl: "https://www.mpt.gov.la", lastReviewed: "2026-07-29" },
  { countryCode: "LA", principleId: 9, score: 35, evidence: "E-signature law exists but implementation limited. No national digital ID. Authentication infrastructure minimal.", sourceUrl: "https://www.mpt.gov.la", lastReviewed: "2026-07-29" },
  { countryCode: "LA", principleId: 12, score: 40, evidence: "No encryption ban. Limited regulatory framework means de facto openness. VPNs available but government monitoring concerns.", sourceUrl: "https://www.mpt.gov.la", lastReviewed: "2026-07-29" },
  { countryCode: "LA", principleId: 10, score: 25, evidence: "Consumer protection law exists but digital commerce provisions minimal. No specialized digital consumer agency. Enforcement extremely limited.", sourceUrl: "https://www.mpt.gov.la", lastReviewed: "2026-07-29" },
  { countryCode: "LA", principleId: 15, score: 30, evidence: "LaoCERT established but capacity limited. Cybersecurity framework developing. Receives international technical assistance.", sourceUrl: "https://www.mpt.gov.la", lastReviewed: "2026-07-29" },
  { countryCode: "LA", principleId: 19, score: 15, evidence: "Limited regulatory transparency. Laws developed with minimal public consultation. One-party state constrains civil society engagement.", sourceUrl: "https://www.mpt.gov.la", lastReviewed: "2026-07-29" },
  { countryCode: "LA", principleId: 20, score: 30, evidence: "State-owned enterprises dominate telecom and digital sectors. Limited private competition. SOE advantages significant.", sourceUrl: "https://www.mpt.gov.la", lastReviewed: "2026-07-29" },
  { countryCode: "LA", principleId: 16, score: 40, evidence: "Standards capacity limited. International standards adopted where recognized. No forced national standards but framework weak.", sourceUrl: "https://www.mpt.gov.la", lastReviewed: "2026-07-29" },
  { countryCode: "LA", principleId: 21, score: 25, evidence: "Copyright law exists but enforcement minimal. No ISP safe harbors. Piracy widespread. IP enforcement capacity extremely limited.", sourceUrl: "https://www.mpt.gov.la", lastReviewed: "2026-07-29" },
  { countryCode: "LA", principleId: 22, score: 30, evidence: "Patent system nascent. Limited examination capacity. PCT accession in progress. Digital innovation patents rare.", sourceUrl: "https://www.mpt.gov.la", lastReviewed: "2026-07-29" },
  { countryCode: "LA", principleId: 23, score: 20, evidence: "Minimal trade secret protection. No cyber trade secret theft framework. IP enforcement generally absent in digital context.", sourceUrl: "https://www.mpt.gov.la", lastReviewed: "2026-07-29" },
  { countryCode: "LA", principleId: 24, score: 30, evidence: "Conformity assessment infrastructure limited. Few accredited labs. Foreign certification recognition inconsistent. Framework developing.", sourceUrl: "https://www.mpt.gov.la", lastReviewed: "2026-07-29" },

  // ══════════════════════════════════════════════════════════════
  // BRUNEI (BN) — CPTPP Member (July 2023), Hybrid
  // ══════════════════════════════════════════════════════════════
  { countryCode: "BN", principleId: 1, score: 55, evidence: "Generally open internet. Content blocking limited primarily to gambling and pornography. Political speech restricted under Sedition Act but digital enforcement moderate.", sourceUrl: "https://www.aiti.gov.bn", lastReviewed: "2026-07-29" },
  { countryCode: "BN", principleId: 11, score: 60, evidence: "Government-linked telcos (DST, imagine) dominate. Limited competition due to small market. Infrastructure adequate but market size constraints.", sourceUrl: "https://www.aiti.gov.bn", lastReviewed: "2026-07-29" },
  { countryCode: "BN", principleId: 17, score: 70, evidence: "CPTPP tariff elimination schedule applies. Most ICT goods duty-free under CPTPP. Small economy with limited domestic manufacturing.", sourceUrl: "https://www.aiti.gov.bn", lastReviewed: "2026-07-29" },
  { countryCode: "BN", principleId: 18, score: 60, evidence: "BDNsw single-window system operational. E-customs improving. Small trade volume means customs relatively efficient.", sourceUrl: "https://www.aiti.gov.bn", lastReviewed: "2026-07-29" },
  { countryCode: "BN", principleId: 2, score: 80, evidence: "No digital customs duties. CPTPP prohibition applies. Small digital economy — minimal revenue at stake.", sourceUrl: "https://www.aiti.gov.bn", lastReviewed: "2026-07-29" },
  { countryCode: "BN", principleId: 3, score: 65, evidence: "CPTPP non-discrimination commitments apply. Generally open to foreign digital services. Small market limits friction.", sourceUrl: "https://www.aiti.gov.bn", lastReviewed: "2026-07-29" },
  { countryCode: "BN", principleId: 4, score: 70, evidence: "PDPO draft provides data transfer framework. CPTPP data flow obligations apply. Small data economy with high compliance standards for financial sector.", sourceUrl: "https://www.aiti.gov.bn", lastReviewed: "2026-07-29" },
  { countryCode: "BN", principleId: 5, score: 75, evidence: "No data localization requirements. CPTPP localization prohibition applies. Cloud services adopted for government under Digital Economy Masterplan.", sourceUrl: "https://www.aiti.gov.bn", lastReviewed: "2026-07-29" },
  { countryCode: "BN", principleId: 13, score: 60, evidence: "CPTPP membership provides digital trade framework. DEFA active participant. Small economy means limited independent digital trade innovation.", sourceUrl: "https://www.aiti.gov.bn", lastReviewed: "2026-07-29" },
  { countryCode: "BN", principleId: 14, score: 70, evidence: "CPTPP service access commitments apply. Open to foreign digital services. Small market with limited regulatory barriers.", sourceUrl: "https://www.aiti.gov.bn", lastReviewed: "2026-07-29" },
  { countryCode: "BN", principleId: 6, score: 75, evidence: "No forced tech transfer. CPTPP prohibition applies. Limited tech sector investment means low incidence. Investment framework open.", sourceUrl: "https://www.aiti.gov.bn", lastReviewed: "2026-07-29" },
  { countryCode: "BN", principleId: 7, score: 70, evidence: "No source code disclosure requirements. CPTPP source code protection applies. AITI regulatory approach non-intrusive.", sourceUrl: "https://www.aiti.gov.bn", lastReviewed: "2026-07-29" },
  { countryCode: "BN", principleId: 8, score: 75, evidence: "Technology-neutral regulations. CPTPP technology choice provisions apply. International standards adopted. Small market means no domestic tech mandates.", sourceUrl: "https://www.aiti.gov.bn", lastReviewed: "2026-07-29" },
  { countryCode: "BN", principleId: 9, score: 60, evidence: "Electronic Transactions Order supports e-signatures. Digital ID under development. Authentication framework improving under Digital Economy Masterplan.", sourceUrl: "https://www.aiti.gov.bn", lastReviewed: "2026-07-29" },
  { countryCode: "BN", principleId: 12, score: 70, evidence: "No encryption restrictions. Cyber Security Brunei focuses on CII protection. No mandatory backdoor requirements. Encryption freely available.", sourceUrl: "https://www.csb.gov.bn", lastReviewed: "2026-07-29" },
  { countryCode: "BN", principleId: 10, score: 60, evidence: "Consumer protection framework developing. PDPO will strengthen digital consumer rights. Limited enforcement history due to small market.", sourceUrl: "https://www.aiti.gov.bn", lastReviewed: "2026-07-29" },
  { countryCode: "BN", principleId: 15, score: 65, evidence: "CSB coordinates cybersecurity. BruCERT incident response. Active in ASEAN cybersecurity cooperation. High standards for financial sector cybersecurity.", sourceUrl: "https://www.csb.gov.bn", lastReviewed: "2026-07-29" },
  { countryCode: "BN", principleId: 19, score: 40, evidence: "Limited public consultation on digital regulations. Absolute monarchy constrains civil society engagement. Stakeholder input channels exist but narrow.", sourceUrl: "https://www.aiti.gov.bn", lastReviewed: "2026-07-29" },
  { countryCode: "BN", principleId: 20, score: 55, evidence: "Government-linked telcos dominate. Small market limits competitive dynamics. SOEs operate commercially but structural advantages exist.", sourceUrl: "https://www.aiti.gov.bn", lastReviewed: "2026-07-29" },
  { countryCode: "BN", principleId: 16, score: 70, evidence: "International standards adopted. No forced national standards. Small market means domestic standards development limited.", sourceUrl: "https://www.aiti.gov.bn", lastReviewed: "2026-07-29" },
  { countryCode: "BN", principleId: 21, score: 55, evidence: "Copyright framework exists. CPTPP IP chapter obligations apply. ISP safe harbors not fully developed. Enforcement moderate.", sourceUrl: "https://www.aiti.gov.bn", lastReviewed: "2026-07-29" },
  { countryCode: "BN", principleId: 22, score: 55, evidence: "Patent system exists. CPTPP patent provisions apply. PCT member. Limited patent examination capacity.", sourceUrl: "https://www.aiti.gov.bn", lastReviewed: "2026-07-29" },
  { countryCode: "BN", principleId: 23, score: 50, evidence: "Trade secret protection developing. CPTPP trade secret provisions apply. Limited enforcement history. No specialized cyber trade secret framework.", sourceUrl: "https://www.aiti.gov.bn", lastReviewed: "2026-07-29" },
  { countryCode: "BN", principleId: 24, score: 60, evidence: "Conformity assessment framework adequate. International certification generally recognized. Small scale limits complexity.", sourceUrl: "https://www.aiti.gov.bn", lastReviewed: "2026-07-29" },

  // ══════════════════════════════════════════════════════════════
  // TIMOR-LESTE (TL) — Open Transfer, ASEAN Observer
  // ══════════════════════════════════════════════════════════════
  { countryCode: "TL", principleId: 1, score: 65, evidence: "Generally open internet. No systematic content blocking. Press freedom respected. Limited state capacity for censorship.", sourceUrl: "https://www.tic.gov.tl", lastReviewed: "2026-07-29" },
  { countryCode: "TL", principleId: 11, score: 45, evidence: "Timor Telecom historically dominant. Market liberalizing gradually. Submarine cable (TLSSC) operational since 2017. Infrastructure developing.", sourceUrl: "https://www.tic.gov.tl", lastReviewed: "2026-07-29" },
  { countryCode: "TL", principleId: 17, score: 60, evidence: "WTO accession process ongoing. ICT tariffs minimal due to limited domestic manufacturing. Relies on imports.", sourceUrl: "https://www.tic.gov.tl", lastReviewed: "2026-07-29" },
  { countryCode: "TL", principleId: 18, score: 40, evidence: "Customs systems basic. ASYCUDA being implemented. Manual processing dominates. Limited trade volume.", sourceUrl: "https://www.tic.gov.tl", lastReviewed: "2026-07-29" },
  { countryCode: "TL", principleId: 2, score: 70, evidence: "No digital customs duties. Limited digital economy means low relevance. Open to international digital trade.", sourceUrl: "https://www.tic.gov.tl", lastReviewed: "2026-07-29" },
  { countryCode: "TL", principleId: 3, score: 65, evidence: "Open to foreign digital services. No discriminatory practices. Limited domestic digital sector means few protectionist pressures.", sourceUrl: "https://www.tic.gov.tl", lastReviewed: "2026-07-29" },
  { countryCode: "TL", principleId: 4, score: 65, evidence: "No data flow restrictions. Draft data protection law under development. International open treaties approach. Limited regulation means de facto openness.", sourceUrl: "https://www.tic.gov.tl", lastReviewed: "2026-07-29" },
  { countryCode: "TL", principleId: 5, score: 75, evidence: "No data localization requirements. Limited digital infrastructure means data often flows internationally. Open approach under National Digital Strategy 2030.", sourceUrl: "https://www.tic.gov.tl", lastReviewed: "2026-07-29" },
  { countryCode: "TL", principleId: 13, score: 45, evidence: "ASEAN observer — not yet full DEFA participant. Aligning with ASEAN frameworks for accession. Digital legal framework nascent.", sourceUrl: "https://www.tic.gov.tl", lastReviewed: "2026-07-29" },
  { countryCode: "TL", principleId: 14, score: 60, evidence: "Open to foreign digital services. Limited regulatory barriers. Small market limits commercial interest in restrictions.", sourceUrl: "https://www.tic.gov.tl", lastReviewed: "2026-07-29" },
  { countryCode: "TL", principleId: 6, score: 70, evidence: "No forced tech transfer. Investment framework open. Limited tech investment means low incidence of pressure.", sourceUrl: "https://www.tic.gov.tl", lastReviewed: "2026-07-29" },
  { countryCode: "TL", principleId: 7, score: 65, evidence: "No source code disclosure requirements. Draft cybercrime law may introduce investigative powers. Current framework non-intrusive.", sourceUrl: "https://www.tic.gov.tl", lastReviewed: "2026-07-29" },
  { countryCode: "TL", principleId: 8, score: 70, evidence: "Technology-neutral. No mandatory domestic technology standards. International standards adopted by default.", sourceUrl: "https://www.tic.gov.tl", lastReviewed: "2026-07-29" },
  { countryCode: "TL", principleId: 9, score: 40, evidence: "E-signature framework underdeveloped. No national digital ID. Authentication infrastructure limited.", sourceUrl: "https://www.tic.gov.tl", lastReviewed: "2026-07-29" },
  { countryCode: "TL", principleId: 12, score: 65, evidence: "No encryption restrictions. VPNs freely available. Limited regulatory framework means de facto openness.", sourceUrl: "https://www.tic.gov.tl", lastReviewed: "2026-07-29" },
  { countryCode: "TL", principleId: 10, score: 35, evidence: "Consumer protection framework underdeveloped. No specialized digital consumer agency. Limited enforcement capacity.", sourceUrl: "https://www.tic.gov.tl", lastReviewed: "2026-07-29" },
  { countryCode: "TL", principleId: 15, score: 35, evidence: "Cybersecurity capacity developing. Limited CERT capabilities. Receiving international assistance. Framework nascent.", sourceUrl: "https://www.tic.gov.tl", lastReviewed: "2026-07-29" },
  { countryCode: "TL", principleId: 19, score: 45, evidence: "Democratic governance enables some public consultation. Limited regulatory capacity constrains stakeholder processes. Civil society engagement possible.", sourceUrl: "https://www.tic.gov.tl", lastReviewed: "2026-07-29" },
  { countryCode: "TL", principleId: 20, score: 55, evidence: "Timor Telecom historically state-linked. Market liberalizing. Limited SOE dominance due to small economy.", sourceUrl: "https://www.tic.gov.tl", lastReviewed: "2026-07-29" },
  { countryCode: "TL", principleId: 16, score: 60, evidence: "International standards adopted. No forced national standards. Limited domestic standards infrastructure.", sourceUrl: "https://www.tic.gov.tl", lastReviewed: "2026-07-29" },
  { countryCode: "TL", principleId: 21, score: 35, evidence: "Copyright framework developing. Enforcement limited. No ISP safe harbors. IP infrastructure nascent.", sourceUrl: "https://www.tic.gov.tl", lastReviewed: "2026-07-29" },
  { countryCode: "TL", principleId: 22, score: 35, evidence: "Patent system under development. Not PCT member. Limited examination capacity. Digital innovation patents extremely rare.", sourceUrl: "https://www.tic.gov.tl", lastReviewed: "2026-07-29" },
  { countryCode: "TL", principleId: 23, score: 30, evidence: "Minimal trade secret protection. No cyber trade secret theft framework. IP enforcement generally absent.", sourceUrl: "https://www.tic.gov.tl", lastReviewed: "2026-07-29" },
  { countryCode: "TL", principleId: 24, score: 35, evidence: "Conformity assessment infrastructure minimal. International certification recognized but framework informal. Capacity developing.", sourceUrl: "https://www.tic.gov.tl", lastReviewed: "2026-07-29" },
];

/** Get all scores, optionally filtered by country code. */
export function getBenchmarkScores(countryCode?: string): BenchmarkScore[] {
  if (countryCode) return BENCHMARK_SCORES.filter((s) => s.countryCode === countryCode);
  return BENCHMARK_SCORES;
}

/** Build a summary for a single country. */
export function getCountryBenchmarkSummary(countryCode: string, countryName: string): BenchmarkCountrySummary {
  const scores = BENCHMARK_SCORES.filter((s) => s.countryCode === countryCode);
  const overallScore = Math.round(scores.reduce((sum, s) => sum + s.score, 0) / scores.length);

  const clusters = BENCHMARK_CLUSTERS.map((cluster) => {
    const clusterScores = scores.filter((s) => (cluster.principles as readonly number[]).includes(s.principleId));
    const averageScore = Math.round(clusterScores.reduce((sum, s) => sum + s.score, 0) / clusterScores.length);
    return {
      clusterId: cluster.id,
      clusterLabel: cluster.label,
      averageScore,
      principleCount: clusterScores.length,
      color: cluster.color,
    };
  });

  return { countryCode, countryName, overallScore, clusters, scores };
}

/** Build summaries for all 11 ASEAN countries. */
export function getAllBenchmarkSummaries(): BenchmarkCountrySummary[] {
  const countries = [
    { code: "SG", name: "Singapore" },
    { code: "MY", name: "Malaysia" },
    { code: "VN", name: "Vietnam" },
    { code: "ID", name: "Indonesia" },
    { code: "TH", name: "Thailand" },
    { code: "PH", name: "Philippines" },
    { code: "MM", name: "Myanmar" },
    { code: "KH", name: "Cambodia" },
    { code: "LA", name: "Laos" },
    { code: "BN", name: "Brunei" },
    { code: "TL", name: "Timor-Leste" },
  ];
  return countries.map((c) => getCountryBenchmarkSummary(c.code, c.name));
}
