import type { ConsumerProtectionPolicy } from "@/types/consumer_protection";

/**
 * Consumer protection policy profiles for ASEAN countries.
 * Sources: National PDP laws, platform governance regulations, OECD.
 * Last reviewed: 2026-07-29
 */
export const CONSUMER_PROTECTION_POLICIES: ConsumerProtectionPolicy[] = [
  {
    id: "cp-sg",
    countryCode: "SG", countryName: "Singapore",
    intermediaryLiability: "PDPA + Protection from Online Falsehoods Act (POFMA). Conditional safe harbor but broad government takedown powers.",
    intermediaryLiabilityScore: 70,
    algorithmicAudit: "AI Verify voluntary framework. No mandatory algorithmic audits. IMDA recommends transparency reporting for foundation models.",
    algorithmicAuditScore: 75,
    breachNotification: "Mandatory data breach notification under PDPA. Organizations must notify PDPC and affected individuals within 3 days of assessment.",
    breachNotificationScore: 85,
    spamRegulation: "Spam Control Act prohibits unsolicited commercial messages. Do Not Call registry operational since 2014.",
    spamRegulationScore: 90,
    darkPatternRestriction: "Consumer Protection (Fair Trading) Act covers unfair practices. No specific dark pattern provisions. General unfair terms protections.",
    darkPatternScore: 60,
    compositeScore: 76,
    lastUpdated: "2026-07-29",
  },
  {
    id: "cp-my",
    countryCode: "MY", countryName: "Malaysia",
    intermediaryLiability: "Communications and Multimedia Act provides conditional immunity. MCMC can direct content removal. No DMCA-style safe harbors.",
    intermediaryLiabilityScore: 55,
    algorithmicAudit: "No algorithmic audit requirements. National AI Roadmap mentions transparency but no binding mandates.",
    algorithmicAuditScore: 40,
    breachNotification: "Mandatory breach notification under PDPA Amendment 2024. Notify PDPD within reasonable timeframe. Individual notification required.",
    breachNotificationScore: 75,
    spamRegulation: "Spam control under CMA. Unsolicited commercial messages regulated but enforcement moderate.",
    spamRegulationScore: 65,
    darkPatternRestriction: "Consumer Protection Act 1999 covers misleading conduct. No specific dark pattern regulation. E-commerce guidelines mention transparent pricing.",
    darkPatternScore: 40,
    compositeScore: 55,
    lastUpdated: "2026-07-29",
  },
  {
    id: "cp-vn",
    countryCode: "VN", countryName: "Vietnam",
    intermediaryLiability: "Decree 52 on E-commerce + Decree 147. Broad platform liability. Foreign platforms must establish local offices. 24-hour content removal.",
    intermediaryLiabilityScore: 30,
    algorithmicAudit: "Draft AI Law proposes mandatory algorithmic audits for AI systems. May require disclosure of training data, model architecture, and decision logic.",
    algorithmicAuditScore: 25,
    breachNotification: "Data breach notification under Cybersecurity Law. Must notify authorities. No clear timeframe or individual notification requirement.",
    breachNotificationScore: 40,
    spamRegulation: "Anti-spam regulations under MIC. SMS and email spam addressed but enforcement inconsistent.",
    spamRegulationScore: 50,
    darkPatternRestriction: "No specific dark pattern legislation. General consumer protection law covers misleading advertising. Digital enforcement nascent.",
    darkPatternScore: 20,
    compositeScore: 33,
    lastUpdated: "2026-07-29",
  },
  {
    id: "cp-id",
    countryCode: "ID", countryName: "Indonesia",
    intermediaryLiability: "MR5 requires PSE to remove content within 24 hours. ITE Law has broad defamation provisions. Platform liability for user content significant.",
    intermediaryLiabilityScore: 35,
    algorithmicAudit: "MR5 provides Kominfo with authority to request algorithmic system information. Draft AI regulation proposes mandatory transparency for public-facing AI.",
    algorithmicAuditScore: 30,
    breachNotification: "PDP Law No. 27/2022 mandates breach notification to PDP Authority and affected individuals within 3x24 hours.",
    breachNotificationScore: 65,
    spamRegulation: "ITE Law and PP 80/2019 regulate electronic messages. Consumer consent required. Enforcement active through Kominfo.",
    spamRegulationScore: 60,
    darkPatternRestriction: "Consumer Protection Law covers unfair business practices. No specific digital dark pattern provisions. OJK regulates financial sector digital practices.",
    darkPatternScore: 35,
    compositeScore: 45,
    lastUpdated: "2026-07-29",
  },
  {
    id: "cp-th",
    countryCode: "TH", countryName: "Thailand",
    intermediaryLiability: "Computer Crime Act has broad intermediary liability for illegal content. PDPA provides data controller obligations. Platform license required under Royal Decree.",
    intermediaryLiabilityScore: 45,
    algorithmicAudit: "ETDA mandates annual algorithmic accountability reports for platforms exceeding 5M active local users under Royal Decree on Digital Platforms.",
    algorithmicAuditScore: 65,
    breachNotification: "PDPA mandates breach notification to PDPC and affected individuals within 72 hours of becoming aware.",
    breachNotificationScore: 80,
    spamRegulation: "Direct Marketing under PDPA. Consent-based framework. PDPC enforcement on unsolicited communications.",
    spamRegulationScore: 70,
    darkPatternRestriction: "ETDA guidelines on fair digital platform practices. Consumer protection board can address deceptive designs. Limited specific dark pattern framework.",
    darkPatternScore: 45,
    compositeScore: 61,
    lastUpdated: "2026-07-29",
  },
  {
    id: "cp-ph",
    countryCode: "PH", countryName: "Philippines",
    intermediaryLiability: "E-Commerce Act provides limited intermediary immunity. DPA holds PICs accountable. Generally balanced approach to platform liability.",
    intermediaryLiabilityScore: 60,
    algorithmicAudit: "No mandatory algorithmic audit requirements. NPC recommends transparency in automated processing but no binding audit framework.",
    algorithmicAuditScore: 35,
    breachNotification: "DPA mandates breach notification to NPC and affected individuals within 72 hours. Strong enforcement by NPC.",
    breachNotificationScore: 80,
    spamRegulation: "Anti-spam provisions under DPA and E-Commerce Act. Opt-out framework. NPC enforcement active.",
    spamRegulationScore: 65,
    darkPatternRestriction: "Consumer Act covers unfair trade practices. No specific digital dark pattern regulation. DTI handles online consumer complaints.",
    darkPatternScore: 40,
    compositeScore: 56,
    lastUpdated: "2026-07-29",
  },
  {
    id: "cp-mm",
    countryCode: "MM", countryName: "Myanmar",
    intermediaryLiability: "No meaningful intermediary liability framework under military rule. Platforms face arbitrary blocking without legal process. Military dictates content moderation.",
    intermediaryLiabilityScore: 10,
    algorithmicAudit: "No algorithmic governance framework. Military controls all digital infrastructure. No transparency requirements exist.",
    algorithmicAuditScore: 5,
    breachNotification: "No data breach notification requirements. Draft Cybersecurity Law provides unrestricted state access, not consumer protection. Individual notification absent.",
    breachNotificationScore: 5,
    spamRegulation: "No spam regulation. Telecommunications under military control. Commercial messaging unregulated.",
    spamRegulationScore: 10,
    darkPatternRestriction: "No consumer protection regulation in digital context. Military rule provides no legal recourse for digital consumers.",
    darkPatternScore: 5,
    compositeScore: 7,
    lastUpdated: "2026-07-29",
  },
  {
    id: "cp-kh",
    countryCode: "KH", countryName: "Cambodia",
    intermediaryLiability: "E-Commerce Law 2019 provides basic framework. Limited intermediary immunity provisions. NIG architecture enables state intervention.",
    intermediaryLiabilityScore: 30,
    algorithmicAudit: "No algorithmic audit framework. No transparency requirements for automated systems. Digital regulation underdeveloped.",
    algorithmicAuditScore: 15,
    breachNotification: "No specific data breach notification requirements. Draft data protection law may include notification provisions.",
    breachNotificationScore: 15,
    spamRegulation: "Limited spam regulation. E-Commerce Law mentions commercial communications but enforcement minimal.",
    spamRegulationScore: 20,
    darkPatternRestriction: "No dark pattern regulation. Consumer protection in digital context minimal. General consumer law does not address digital-specific deceptive practices.",
    darkPatternScore: 10,
    compositeScore: 18,
    lastUpdated: "2026-07-29",
  },
  {
    id: "cp-la",
    countryCode: "LA", countryName: "Laos",
    intermediaryLiability: "Limited intermediary liability framework. E-Transactions Law provides basic provisions. Regulatory capacity constrained.",
    intermediaryLiabilityScore: 20,
    algorithmicAudit: "No algorithmic governance framework. Digital regulation nascent. No AI-specific regulation.",
    algorithmicAuditScore: 10,
    breachNotification: "No data breach notification requirements. Draft data protection law under development.",
    breachNotificationScore: 10,
    spamRegulation: "Minimal spam regulation. Electronic commerce regulation underdeveloped.",
    spamRegulationScore: 15,
    darkPatternRestriction: "No dark pattern regulation. Consumer protection capacity extremely limited.",
    darkPatternScore: 10,
    compositeScore: 13,
    lastUpdated: "2026-07-29",
  },
  {
    id: "cp-bn",
    countryCode: "BN", countryName: "Brunei",
    intermediaryLiability: "PDPO draft provides data controller obligations. Electronic Transactions Order has limited intermediary provisions. Generally non-interventionist approach.",
    intermediaryLiabilityScore: 50,
    algorithmicAudit: "No algorithmic audit requirements. Digital Economy Masterplan mentions AI governance but no binding frameworks yet.",
    algorithmicAuditScore: 30,
    breachNotification: "PDPO draft includes breach notification provisions. Framework under development but aligned with international standards.",
    breachNotificationScore: 55,
    spamRegulation: "Spam regulation under Electronic Transactions Order. Limited enforcement due to small market size.",
    spamRegulationScore: 45,
    darkPatternRestriction: "No specific dark pattern regulation. Consumer protection framework developing under Digital Economy Masterplan.",
    darkPatternScore: 25,
    compositeScore: 41,
    lastUpdated: "2026-07-29",
  },
  {
    id: "cp-tl",
    countryCode: "TL", countryName: "Timor-Leste",
    intermediaryLiability: "Limited intermediary liability framework. Draft cybercrime law may address platform obligations. Current regulation minimal.",
    intermediaryLiabilityScore: 25,
    algorithmicAudit: "No algorithmic governance framework. Digital regulation nascent. ICT infrastructure developing.",
    algorithmicAuditScore: 10,
    breachNotification: "No specific breach notification requirements. Draft data protection law under development.",
    breachNotificationScore: 10,
    spamRegulation: "Minimal spam regulation. Telecommunications regulation developing.",
    spamRegulationScore: 15,
    darkPatternRestriction: "No dark pattern regulation. Consumer protection capacity limited. Digital commerce framework nascent.",
    darkPatternScore: 10,
    compositeScore: 14,
    lastUpdated: "2026-07-29",
  },
];

/** Get all consumer protection policies, optionally filtered by country. */
export function getConsumerProtectionPolicies(countryCode?: string): ConsumerProtectionPolicy[] {
  if (countryCode) return CONSUMER_PROTECTION_POLICIES.filter((p) => p.countryCode === countryCode);
  return CONSUMER_PROTECTION_POLICIES;
}
